namespace AC2RE.Definitions;

// Enum LandscapeHeightRelativeType::Type
public enum LandscapeHeightRelativeType : uint {
    LAND_HEIGHT, // LAND_HEIGHT_RELATIVE
    WATER_HEIGHT, // WATER_HEIGHT_RELATIVE
    ZERO_HEIGHT, // ZERO_HEIGHT_RELATIVE
    MAX_BLOCK_HEIGHT, // MAX_BLOCK_HEIGHT_RELATIVE
    MIN_BLOCK_HEIGHT, // MIN_BLOCK_HEIGHT_RELATIVE
    AVE_BLOCK_HEIGHT, // AVE_BLOCK_HEIGHT_RELATIVE
    MAX_CELL_HEIGHT, // MAX_CELL_HEIGHT_RELATIVE
    MIN_CELL_HEIGHT, // MIN_CELL_HEIGHT_RELATIVE
    AVE_CELL_HEIGHT, // AVE_CELL_HEIGHT_RELATIVE
    FRAME, // FRAME_RELATIVE
    INVALID, // INVALID
}
