using System.Collections.Generic;

namespace AC2RE.Definitions {

    public class DbTypeDef {

        public enum DatType {
            PORTAL,
            CELL,
            LOCAL,
        }

        public static readonly Dictionary<DbType, DbTypeDef> TYPE_TO_DEF = new() {
            {
                DbType.LANDBLOCKINFO,
                new() {
                    baseDid = new(0),
                    topDid = new(0),
                    extension = ".lbi",
                    packVersion = 1,
                    updateType = DbUpdateType.Dynamic,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = true,
                    isLocalType = false,
                    strDataDir = "lbi",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.LIGHTINFO,
                new() {
                    baseDid = new(0),
                    topDid = new(0),
                    extension = ".lightinfo",
                    packVersion = 1,
                    updateType = DbUpdateType.Dynamic,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = true,
                    isLocalType = false,
                    strDataDir = "lbi",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 8,
                    freelistMaxSize = 16,
                }
            },
            {
                DbType.LBO,
                new() {
                    baseDid = new(0),
                    topDid = new(0),
                    extension = ".lbo",
                    packVersion = 1,
                    updateType = DbUpdateType.Dynamic,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "lbo",
                    isClientType = false,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SHELL,
                new() {
                    baseDid = new(0),
                    topDid = new(0),
                    extension = ".shell",
                    packVersion = 1,
                    updateType = DbUpdateType.Dynamic,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "shell",
                    isClientType = false,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.LIGHTCACHE,
                new() {
                    baseDid = new(0),
                    topDid = new(0),
                    extension = ".lightcache",
                    packVersion = 1,
                    updateType = DbUpdateType.Dynamic,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "shell",
                    isClientType = false,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.PATHMAP,
                new() {
                    baseDid = new(0),
                    topDid = new(0),
                    extension = ".pathmap",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = true,
                    isLocalType = false,
                    strDataDir = "pathmap",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.CELLMESH,
                new() {
                    baseDid = new(0x01000000),
                    topDid = new(0x01FFFFFF),
                    extension = ".cellmesh",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "cellmesh",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SCENE,
                new() {
                    baseDid = new(0x02000000),
                    topDid = new(0x02FFFFFF),
                    extension = ".scn",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "scn",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.ANIMMAP,
                new() {
                    baseDid = new(0x03000000),
                    topDid = new(0x03FFFFFF),
                    extension = ".animmap",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "animmap",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SETUP,
                new() {
                    baseDid = new(0x04000000),
                    topDid = new(0x04FFFFFF),
                    extension = ".set",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "setup",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.DBANIMATOR,
                new() {
                    baseDid = new(0x05000000),
                    topDid = new(0x05FFFFFF),
                    extension = ".anm",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "anim",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.MESH,
                new() {
                    baseDid = new(0x06000000),
                    topDid = new(0x06FFFFFF),
                    extension = ".mesh",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "mesh",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.QUALITY_FILTER,
                new() {
                    baseDid = new(0x0A000000),
                    topDid = new(0x0AFFFFFF),
                    extension = ".wqf",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "weenie/filters",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.WAVE,
                new() {
                    baseDid = new(0x0C000000),
                    topDid = new(0x0CFFFFFF),
                    extension = ".wav",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "sound",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.FILE2ID_TABLE,
                new() {
                    baseDid = new(0x0E000003),
                    topDid = new(0x0E000003),
                    extension = "",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = false,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.PLACES_TABLE,
                new() {
                    baseDid = new(0x0E000004),
                    topDid = new(0x0E000004),
                    extension = ".places",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "weenie",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.TABOO_TABLE,
                new() {
                    baseDid = new(0x0EBADA55),
                    topDid = new(0x0EBADA55),
                    extension = ".taboo",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "weenie",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.REGION,
                new() {
                    baseDid = new(0x0F000000),
                    topDid = new(0x0FFFFFFF),
                    extension = ".rgn",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SOUND_DESC,
                new() {
                    baseDid = new(0x10000000),
                    topDid = new(0x10FFFFFF),
                    extension = ".sod",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SCENE_DESC,
                new() {
                    baseDid = new(0x11000000),
                    topDid = new(0x11FFFFFF),
                    extension = ".scd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.TERRAIN_DESC,
                new() {
                    baseDid = new(0x12000000),
                    topDid = new(0x12FFFFFF),
                    extension = ".trd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SURFACE_DESC,
                new() {
                    baseDid = new(0x13000000),
                    topDid = new(0x13FFFFFF),
                    extension = ".sfd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.ENCOUNTER_DESC,
                new() {
                    baseDid = new(0x14000000),
                    topDid = new(0x14FFFFFF),
                    extension = ".end",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SKY_DESC,
                new() {
                    baseDid = new(0x15000000),
                    topDid = new(0x15FFFFFF),
                    extension = ".skd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.WATER_DESC,
                new() {
                    baseDid = new(0x16000000),
                    topDid = new(0x16FFFFFF),
                    extension = ".wtd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.FOG_DESC,
                new() {
                    baseDid = new(0x17000000),
                    topDid = new(0x17FFFFFF),
                    extension = ".fgd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.PROPERTY_DESC,
                new() {
                    baseDid = new(0x18000000),
                    topDid = new(0x18FFFFFF),
                    extension = ".prd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.BLOCK_MAP,
                new() {
                    baseDid = new(0x19000000),
                    topDid = new(0x19FFFFFF),
                    extension = ".bmd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.DAY_DESC,
                new() {
                    baseDid = new(0x1A000000),
                    topDid = new(0x1AFFFFFF),
                    extension = ".dyd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.KEYMAP,
                new() {
                    baseDid = new(0x1D000000),
                    topDid = new(0x1DFFFFFF),
                    extension = ".keymap",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "keymap",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.FX_TABLE,
                new() {
                    baseDid = new(0x1E000000),
                    topDid = new(0x1EFFFFFF),
                    extension = ".fxtable",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "fxtable",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.VISUAL_DESC,
                new() {
                    baseDid = new(0x1F000000),
                    topDid = new(0x1FFFFFFF),
                    extension = ".vd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "vdesc",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.APPEARANCE,
                new() {
                    baseDid = new(0x20000000),
                    topDid = new(0x20FFFFFF),
                    extension = ".apr",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "appearance",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.UI_SCENE,
                new() {
                    baseDid = new(0x21000000),
                    topDid = new(0x21FFFFFF),
                    extension = ".uiscene",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "ui/uiscene",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.UI_LAYOUT,
                new() {
                    baseDid = new(0x22000000),
                    topDid = new(0x22FFFFFF),
                    extension = ".uil",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "ui/layout",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.ENUM_MAPPER,
                new() {
                    baseDid = new(0x23000000),
                    topDid = new(0x23FFFFFF),
                    extension = ".emp",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "emp",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.MUSICDESC,
                new() {
                    baseDid = new(0x24000000),
                    topDid = new(0x24FFFFFF),
                    extension = ".mid",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "sound",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = true,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.STRING_TABLE,
                new() {
                    baseDid = new(0x25000000),
                    topDid = new(0x26FFFFFF),
                    extension = ".stt",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "stringtable",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.FILEFORMAT,
                new() {
                    baseDid = new(0x27000000),
                    topDid = new(0x27FFFFFF),
                    extension = ".fmt",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "fmt",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.INPUTMAPPER,
                new() {
                    baseDid = new(0x28000000),
                    topDid = new(0x28FFFFFF),
                    extension = ".imp",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "emp/idmap",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.ENVINFO,
                new() {
                    baseDid = new(0x29000000),
                    topDid = new(0x29FFFFFF),
                    extension = ".snv",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "sound/envinfo",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.SOUNDINFO,
                new() {
                    baseDid = new(0x2A000000),
                    topDid = new(0x2AFFFFFF),
                    extension = ".sif",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "sound",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.RENDERMATERIAL,
                new() {
                    baseDid = new(0x2B000000),
                    topDid = new(0x2BFFFFFF),
                    extension = ".mat",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "materials",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.MUSICINFO,
                new() {
                    baseDid = new(0x2C000000),
                    topDid = new(0x2CFFFFFF),
                    extension = ".mif",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "sound",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.CHARTEMPLATE,
                new() {
                    baseDid = new(0x2F000000),
                    topDid = new(0x2FFFFFFF),
                    extension = ".ctp",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "animsys",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.MATERIALMODIFIER,
                new() {
                    baseDid = new(0x30000000),
                    topDid = new(0x30FFFFFF),
                    extension = ".mm",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "materials",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.MATERIALINSTANCE,
                new() {
                    baseDid = new(0x31000000),
                    topDid = new(0x31FFFFFF),
                    extension = ".mi",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "materials",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.MOTIONINTERPDESC,
                new() {
                    baseDid = new(0x32000000),
                    topDid = new(0x32FFFFFF),
                    extension = ".midesc",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "animsys",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.MASTER_PROPERTY,
                new() {
                    baseDid = new(0x34000000),
                    topDid = new(0x34FFFFFF),
                    extension = ".mpr",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "emp/property",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.GAME_TIME,
                new() {
                    baseDid = new(0x35000000),
                    topDid = new(0x35FFFFFF),
                    extension = ".gmt",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.LANDSCAPE_DEFS,
                new() {
                    baseDid = new(0x36000000),
                    topDid = new(0x36FFFFFF),
                    extension = ".lnd",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.PHYSICS_MATERIAL,
                new() {
                    baseDid = new(0x37000000),
                    topDid = new(0x37FFFFFF),
                    extension = ".pmat",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "pmat",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.OBSTACLE_DESC,
                new() {
                    baseDid = new(0x38000000),
                    topDid = new(0x38FFFFFF),
                    extension = ".obstacledesc",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "obsdesc",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.PSDESC,
                new() {
                    baseDid = new(0x39000000),
                    topDid = new(0x39FFFFFF),
                    extension = ".psdesc",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "particles",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.RENDERTEXTURE,
                new() {
                    baseDid = new(0x40000000),
                    topDid = new(0x400FFFFF),
                    extension = ".texture",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "textures",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.RENDERTEXTURE_LOCAL,
                new() {
                    baseDid = new(0x40100000),
                    topDid = new(0x40FFFFFF),
                    extension = ".texture_local",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "textures",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.RENDERSURFACE,
                new() {
                    baseDid = new(0x41000000),
                    topDid = new(0x410FFFFF),
                    extension = ".dds",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "surfaces",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = true,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 256,
                    freelistMaxSize = 512,
                }
            },
            {
                DbType.RENDERSURFACE_LOCAL,
                new() {
                    baseDid = new(0x41100000),
                    topDid = new(0x41FFFFFF),
                    extension = ".dds_local",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "surfaces",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = true,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 256,
                    freelistMaxSize = 512,
                }
            },
            {
                DbType.FONT,
                new() {
                    baseDid = new(0x42000000),
                    topDid = new(0x42000FFF),
                    extension = ".font",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "fonts",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.FONT_LOCAL,
                new() {
                    baseDid = new(0x42001000),
                    topDid = new(0x42FFFFFF),
                    extension = ".font_local",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "fonts",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.BEHAVIORTABLE,
                new() {
                    baseDid = new(0x44000000),
                    topDid = new(0x44FFFFFF),
                    extension = ".behaviortable",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "behaviortable",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.ENTITYGROUP,
                new() {
                    baseDid = new(0x46000000),
                    topDid = new(0x46FFFFFF),
                    extension = ".entitygroup",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "entitygroup",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.ENTITYDESC,
                new() {
                    baseDid = new(0x47000000),
                    topDid = new(0x47FFFFFF),
                    extension = ".entity",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "entity",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 64,
                    freelistMaxSize = 128,
                }
            },
            {
                DbType.ACTIONMAP,
                new() {
                    baseDid = new(0x51000000),
                    topDid = new(0x51FFFFFF),
                    extension = ".actionmap",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "actionmap",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.CDB_TABLE,
                new() {
                    baseDid = new(0x52000000),
                    topDid = new(0x527FFFFF),
                    extension = ".cdb",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "emp/contentor",
                    isClientType = false,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.PERFORMANCE,
                new() {
                    baseDid = new(0x52800000),
                    topDid = new(0x52FFFFFF),
                    extension = ".prf",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "emp/perfmon",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.VALIDMODES,
                new() {
                    baseDid = new(0x54000000),
                    topDid = new(0x54FFFFFF),
                    extension = ".validmodes",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "animsys",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.CAMERA_FX,
                new() {
                    baseDid = new(0x55000000),
                    topDid = new(0x55FFFFFF),
                    extension = ".cfx",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "anim",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.WLIB,
                new() {
                    baseDid = new(0x56000000),
                    topDid = new(0x56FFFFFF),
                    extension = ".wlib",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "weenie/wsl",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = true,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.FXSCRIPT,
                new() {
                    baseDid = new(0x57000000),
                    topDid = new(0x57FFFFFF),
                    extension = ".fxscript",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "fxscript",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.STRING_STATE,
                new() {
                    baseDid = new(0x58000000),
                    topDid = new(0x58FFFFFF),
                    extension = ".sti",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "stringtable",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.DETAILMAP_DESC,
                new() {
                    baseDid = new(0x59000000),
                    topDid = new(0x59000FFF),
                    extension = ".detailmap",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.MAPNOTE_DESC,
                new() {
                    baseDid = new(0x5900F000),
                    topDid = new(0x59FFFFFF),
                    extension = ".mapnotes",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "landscape",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.CONVERSATION_TREE,
                new() {
                    baseDid = new(0x60000000),
                    topDid = new(0x60FFFFFF),
                    extension = ".conversation",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "conversation",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.ENCODED_WAV,
                new() {
                    baseDid = new(0x61000000),
                    topDid = new(0x61FFFFFF),
                    extension = ".wbaseDid",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = false,
                    isCellType = false,
                    isLocalType = true,
                    strDataDir = "sound",
                    isClientType = true,
                    isServerType = false,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 1,
                    freelistMaxSize = 32,
                }
            },
            {
                DbType.DBCATEGORIES,
                new() {
                    baseDid = new(0x62000000),
                    topDid = new(0x62FFFFFF),
                    extension = ".dbcategories",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "emp",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            {
                DbType.WSTATE,
                new() {
                    baseDid = new(0x6F000000),
                    topDid = new(0x7FFFFFFF),
                    extension = ".wc",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = true,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "weenie",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.QUALITIES,
                new() {
                    baseDid = new(0x80000000),
                    topDid = new(0x81FFFFFF),
                    extension = "",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = false,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = true,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 128,
                    freelistMaxSize = 256,
                }
            },
            {
                DbType.DATFILEDATA,
                new() {
                    baseDid = new(0xFFFF0000),
                    topDid = new(0xFFFFFFFF),
                    extension = "",
                    packVersion = 1,
                    updateType = DbUpdateType.Patch,
                    hasFile = false,
                    isPortalType = true,
                    isCellType = false,
                    isLocalType = false,
                    strDataDir = "",
                    isClientType = true,
                    isServerType = true,
                    isEngineType = true,
                    isDidPackedToDats = false,
                    isWbEditable = false,
                    isCategorized = false,
                    freelistRecycle = false,
                    freelistShrink = true,
                    freelistIdealSize = 32,
                    freelistMaxSize = 64,
                }
            },
            // NOTE: Unofficial entries
            {
                DbType.LANDBLOCKDATA,
                new() {
                    extension = ".lbd",
                    isPortalType = false,
                    isCellType = true,
                    isLocalType = false,
                    strDataDir = "lbd",
                }
            },
            {
                DbType.ENVCELL,
                new() {
                    extension = ".envcell",
                    isPortalType = false,
                    isCellType = true,
                    isLocalType = false,
                    strDataDir = "envcell",
                }
            },
        };

        public DataId baseDid;
        public DataId topDid;
        public string extension;
        public uint packVersion;
        public DbUpdateType updateType;
        public bool hasFile;
        public bool isPortalType;
        public bool isCellType;
        public bool isLocalType;
        public string strDataDir;
        public bool isClientType;
        public bool isServerType;
        public bool isEngineType;
        public bool isDidPackedToDats;
        public bool isWbEditable;
        public bool isCategorized;
        public bool freelistRecycle;
        public bool freelistShrink;
        public uint freelistIdealSize;
        public uint freelistMaxSize;

        public bool contains(DataId did) {
            return contains(did.id);
        }

        public bool contains(uint did) {
            return did >= baseDid.id && did <= topDid.id;
        }

        public static DbType getType(DatType datType, DataId did) {
            return getType(datType, did.id);
        }

        public static DbType getType(DatType datType, uint did) {
            DbType dbType = DbType.UNDEFINED;

            foreach ((DbType entryType, DbTypeDef entryTypeDef) in TYPE_TO_DEF) {
                if (entryTypeDef.contains(did)) {
                    dbType = entryType;
                }
            }

            if (dbType != DbType.DATFILEDATA) {
                if (datType == DatType.CELL) {
                    dbType = (did & 0xFFFF) switch {
                        0xFFFC => DbType.LIGHTINFO,
                        0xFFFD => DbType.PATHMAP,
                        0xFFFE => DbType.LANDBLOCKINFO,
                        0xFFFF => DbType.LANDBLOCKDATA,
                        _ => DbType.ENVCELL,
                    };
                }
            }

            return dbType;
        }
    }
}
