namespace AC2RE.Definitions;

// Enum RMFieldType
public enum RMFieldType : uint {
    AMBIENT, // RMFIELD_LAYER_AMBIENT
    DIFFUSE, // RMFIELD_LAYER_DIFFUSE
    SPECULAR, // RMFIELD_LAYER_SPECULAR
    SPECULARPOWER, // RMFIELD_LAYER_SPECULARPOWER
    RESERVED, // RMFIELD_LAYER_xx_RESERVED_xx
    CULLMODE, // RMFIELD_LAYER_CULLMODE
    DEPTHTEST, // RMFIELD_LAYER_DEPTHTEST
    DEPTHWRITE, // RMFIELD_LAYER_DEPTHWRITE
    ALPHATEST, // RMFIELD_LAYER_ALPHATEST
    ALPHATESTREF, // RMFIELD_LAYER_ALPHATESTREF
    STAGE_TEXTURE, // RMFIELD_LAYER_STAGE_TEXTURE
    STAGE_ADDRESSMODEU, // RMFIELD_LAYER_STAGE_ADDRESSMODEU
    STAGE_ADDRESSMODEV, // RMFIELD_LAYER_STAGE_ADDRESSMODEV
    MOD_ORIGIN_XTRANSLATE, // RMFIELD_LAYER_MOD_ORIGIN_XTRANSLATE
    MOD_ORIGIN_YTRANSLATE, // RMFIELD_LAYER_MOD_ORIGIN_YTRANSLATE
    MOD_ORIGIN_ZTRANSLATE, // RMFIELD_LAYER_MOD_ORIGIN_ZTRANSLATE
    MOD_ORIGIN_XSCALE, // RMFIELD_LAYER_MOD_ORIGIN_XSCALE
    MOD_ORIGIN_YSCALE, // RMFIELD_LAYER_MOD_ORIGIN_YSCALE
    MOD_ORIGIN_ZSCALE, // RMFIELD_LAYER_MOD_ORIGIN_ZSCALE
    MOD_ORIGIN_ORIGINPHASE, // RMFIELD_LAYER_MOD_ORIGIN_ORIGINPHASE
    MOD_ORIGIN_NORMALPHASE, // RMFIELD_LAYER_MOD_ORIGIN_NORMALPHASE
    MOD_NORMAL_XTRANSLATE, // RMFIELD_LAYER_MOD_NORMAL_XTRANSLATE
    MOD_NORMAL_YTRANSLATE, // RMFIELD_LAYER_MOD_NORMAL_YTRANSLATE
    MOD_NORMAL_ZTRANSLATE, // RMFIELD_LAYER_MOD_NORMAL_ZTRANSLATE
    MOD_NORMAL_XSCALE, // RMFIELD_LAYER_MOD_NORMAL_XSCALE
    MOD_NORMAL_YSCALE, // RMFIELD_LAYER_MOD_NORMAL_YSCALE
    MOD_NORMAL_ZSCALE, // RMFIELD_LAYER_MOD_NORMAL_ZSCALE
    MOD_NORMAL_ORIGINPHASE, // RMFIELD_LAYER_MOD_NORMAL_ORIGINPHASE
    MOD_NORMAL_NORMALPHASE, // RMFIELD_LAYER_MOD_NORMAL_NORMALPHASE
    MOD_DIFFUSE_R, // RMFIELD_LAYER_MOD_DIFFUSE_R
    MOD_DIFFUSE_G, // RMFIELD_LAYER_MOD_DIFFUSE_G
    MOD_DIFFUSE_B, // RMFIELD_LAYER_MOD_DIFFUSE_B
    MOD_DIFFUSE_A, // RMFIELD_LAYER_MOD_DIFFUSE_A
    MOD_UVTRANSLATE_UTRANSLATE, // RMFIELD_LAYER_MOD_UVTRANSLATE_UTRANSLATE
    MOD_UVTRANSLATE_VTRANSLATE, // RMFIELD_LAYER_MOD_UVTRANSLATE_VTRANSLATE
    MOD_UVROTATE_ROTATE, // RMFIELD_LAYER_MOD_UVROTATE_ROTATE
    MOD_UVSCALE_USCALE, // RMFIELD_LAYER_MOD_UVSCALE_USCALE
    MOD_UVSCALE_VSCALE, // RMFIELD_LAYER_MOD_UVSCALE_VSCALE
}
