using System.Collections.Generic;

namespace AC2E.Def {

    public static class ItemPackages {

        public static readonly HashSet<PackageType> ALCHEMY_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Alembic,
            PackageType.Cruse,
            PackageType.Phial,
            PackageType.VialBlistering,
            PackageType.VialCaustic,
            PackageType.VialHumanVirulentGoldenAge,
            PackageType.VialVirulent,

            PackageType.VialHumanVirulentAncients,
            PackageType.VialHumanVirulentSunBlaze,
        };

        public static readonly HashSet<PackageType> AXE_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.AxeDrudgePick,
            PackageType.AxeGurogCanescent,
            PackageType.AxeGurogCanescentLeft,
            PackageType.AxeGurogCaptain,
            PackageType.AxeGurogCaptainLeft,
            PackageType.AxeGurogChampion,
            PackageType.AxeGurogChampionLeft,
            PackageType.AxeGurogDire,
            PackageType.AxeGurogDireLeft,
            PackageType.AxeGurogEmissary,
            PackageType.AxeGurogGladiator,
            PackageType.AxeGurogGladiatorLeft,
            PackageType.AxeGurogGreat,
            PackageType.AxeGurogGreatLeft,
            PackageType.AxeGurogGrunt,
            PackageType.AxeGurogGruntLeft,
            PackageType.AxeGurogHenchman,
            PackageType.AxeGurogHoary,
            PackageType.AxeGurogHoaryLeft,
            PackageType.AxeGurogLackey,
            PackageType.AxeGurogMinion,
            PackageType.AxeGurogMountainKing,
            PackageType.AxeGurogMountainKingLeft,
            PackageType.AxeGurogWarlord,
            PackageType.AxeGurogWarlordLeft,
            PackageType.AxeLugianCrusaderHatchet,
            PackageType.AxeLugianExecutioner,
            PackageType.AxeLugianHatchet,
            PackageType.AxeLugianRuneAxe,
            PackageType.AxeLugianStoneAxe,
            PackageType.AxeSclavusEssaLord,
            PackageType.AxeSclavusFaisi,
            PackageType.AxeSclavusFaisiLord,
            PackageType.AxeSclavusSata,
            PackageType.AxeSclavusUlu,
            PackageType.AxeSclavusUluLord,
            PackageType.AxeSpine,
        };

        public static readonly HashSet<PackageType> CESTAS_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.CestasTumerok,
            PackageType.CestasTumerokBlade,
            PackageType.CestasTumerokFang,
            PackageType.CestasTumerokSkull,
            PackageType.CestasTumerokSkullGoldenAge,
            PackageType.CestasTumerokTusk,

            PackageType.CestasTumerokSkullAncients,
            PackageType.CestasTumerokSkullSunBlaze,
        };

        public static readonly HashSet<PackageType> DEATH_PORTAL_PACKAGES = new HashSet<PackageType> {
            PackageType.PortalCellDomCenter,
            PackageType.PortalCellDomMaze,
            PackageType.PortalCellDomZone,
            PackageType.VirindiPortalspace,
        };

        public static readonly HashSet<PackageType> DOOR_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.DoorBarred,
            PackageType.DoorEmperianHaunted,
            PackageType.DoorEmperianMossy,
            PackageType.DoorHuman,
            PackageType.DoorHumanLarge,
            PackageType.DoorMine,
            PackageType.DoorStone,
            PackageType.DoorTreasuryEeruk,
            PackageType.DoorVirindi,
        };

        public static readonly HashSet<PackageType> DRUM_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.DrumBuadrenRain,
            PackageType.DrumBuadrenTotemic,
            PackageType.DrumTumerok,
            PackageType.DrumTumerokAncestor,
            PackageType.DrumTumerokAncestorGoldenAge,
            PackageType.DrumTumerokAncient,
            PackageType.DrumTumerokDjembeWasp,
            PackageType.DrumTumerokDjembeWharu,
            PackageType.DrumTumerokFury,
            PackageType.DrumTumerokRain,
            PackageType.DrumTumerokRiver,
            PackageType.DrumTumerokSpirit,
            PackageType.DrumTumerokStarter,
            PackageType.DrumTumerokStump,
            PackageType.DrumTumerokWind,
            PackageType.DrumUnaro,

            PackageType.DrumTumerokAncestorAncients,
            PackageType.DrumTumerokAncestorSunBlaze,
        };

        public static readonly HashSet<PackageType> FROGSTAVE_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.FrogstaveAcolytesFocus,
            PackageType.FrogstaveGuidesFocus,
            PackageType.FrogstaveInitiatesFocus,
            PackageType.FrogstaveSpiritseeker,
            PackageType.FrogstaveSpiritseekerGoldenAge,
            PackageType.FrogstaveTravelersFocus,

            PackageType.FrogstaveSpiritseekerAncients,
            PackageType.FrogstaveSpiritseekerSunBlaze,
        };

        public static readonly HashSet<PackageType> GENERIC_PORTAL_PACKAGES = new HashSet<PackageType> {
            PackageType.DungeonPortal_BTD,
            PackageType.GenericPortal_Blue,
            PackageType.GenericPortal_Green,
            PackageType.GenericPortal_Pink,
            PackageType.GenericPortal_Purple,
            PackageType.GenericPortal_Red,
            PackageType.GenericPortal_Teal,
            PackageType.GenericPortal_Yellow,
            PackageType.GenericShardRoomPortal,
            PackageType.GenericVault,
        };

        public static readonly HashSet<PackageType> GLYPH_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Glyph_Ariaki,
            PackageType.Glyph_Arwic,
            PackageType.Glyph_Citadel,
            PackageType.Glyph_Cobalt,
            PackageType.Glyph_EmpyreanTrainingHall,
            PackageType.Glyph_Esper,
            PackageType.Glyph_Faralie,
            PackageType.Glyph_Gevoth,
            PackageType.Glyph_Kydi,
            PackageType.Glyph_Lostwish,
            PackageType.Glyph_Lumari,
            PackageType.Glyph_Madcrone,
            PackageType.Glyph_Malthabbor,
            PackageType.Glyph_Naderu,
            PackageType.Glyph_Nepeth,
            PackageType.Glyph_Oriad,
            PackageType.Glyph_Prosper,
            PackageType.Glyph_Stoneshadow,
            PackageType.Glyph_Thusik,
            PackageType.Glyph_TouTou,
            PackageType.Glyph_TrainingHall,
            PackageType.Glyph_Vesayen,
            PackageType.Glyph_Winterhollows,
            PackageType.GlyphCragstone,
        };

        public static readonly HashSet<PackageType> KEY_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Key_AriakiVaultDoor,
            PackageType.Key_CitadelVaultDoor,
            PackageType.Key_CobaltVaultDoor,
            PackageType.Key_FaralieVaultDoor,
            PackageType.Key_GevothVaultDoor1,
            PackageType.Key_GevothVaultDoor2,
            PackageType.Key_KydiVaultDoor,
            PackageType.Key_LumariVaultDoor,
            PackageType.Key_MalthabborVaultDoor1,
            PackageType.Key_MalthabborVaultDoor2,
            PackageType.Key_NaderuVaultDoor,
            PackageType.Key_NepethVaultDoor,
            PackageType.Key_OriadVaultDoor,
            PackageType.Key_StoneshadowVaultDoor,
            PackageType.Key_ThusikVaultDoor,
            PackageType.Key_TouTouVaultDoor,
            PackageType.Key_VesayenVaultDoor,
            PackageType.Key_WinterhollowsVaultDoor,
            PackageType.KeyTreasuryEeruk,
        };

        public static readonly HashSet<PackageType> MAP_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.LinvakMiningMapTemplate,
            PackageType.OmishanMiningMapTemplate,
            PackageType.OstethMiningMapTemplate,
        };

        public static readonly HashSet<PackageType> MINE_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.CrystalMineTemplate,
            PackageType.GraniteMineTemplate,
            PackageType.GypsumMineTemplate,
            PackageType.IronMineTemplate,
            PackageType.KaolinMineTemplate,
            PackageType.MeatMineTemplate,
            PackageType.OakMineTemplate,
            PackageType.SilverMineTemplate,
            PackageType.SlateMineTemplate,
            PackageType.StoneMineTemplate,
            PackageType.WoodMineTemplate,
        };

        public static readonly HashSet<PackageType> MINING_TOOL_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Chisel,
            PackageType.GenericTool,
            PackageType.Hatchet,
            PackageType.Mattock,
            PackageType.Pickaxe,
            PackageType.RockHammer,
        };

        public static readonly HashSet<PackageType> MOTE_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Mote_Acid,
            PackageType.Mote_Brimstone,
            PackageType.Mote_CelestialMatter,
            PackageType.Mote_Chorizite,
            PackageType.Mote_Crystal,
            PackageType.Mote_DarkMetal,
            PackageType.Mote_Elariwood,
            PackageType.Mote_EnergyLattice,
            PackageType.Mote_Gemstone,
            PackageType.Mote_Iron,
            PackageType.Mote_Obsidian,
            PackageType.Mote_Pyreal,
            PackageType.Mote_Relic,
            PackageType.Mote_Silver,
            PackageType.Mote_Stone,
            PackageType.Mote_Wood,
            PackageType.TestMote,
        };

        public static readonly HashSet<PackageType> POTION_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.AmuletSeeking,
            PackageType.BrothOfTanacha,
            PackageType.Darkstone,
            PackageType.EggArmoredilloSteppeGuardian,
            PackageType.FoodForaged,
            PackageType.PotionHealing,
            PackageType.PotionHealWeak,
            PackageType.PotionLesserHealing,
            PackageType.PotionMagic,
            PackageType.PotionTrainingHallHaste,
            PackageType.PotionTrainingHallHealing,
            PackageType.PotionTrainingHallThorns,
            PackageType.RattleBlindDeath,
            PackageType.SanguineFangUnguent,
            PackageType.WaterDivined,
        };

        public static readonly HashSet<PackageType> ROAD_SIGN_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.AnkoroRoadSign,
            PackageType.AnkoroTownSign,
            PackageType.ArhovasRoadSign,
            PackageType.ArhovasTownSign,
            PackageType.ArwicRoadSign,
            PackageType.ArwicTownSign,
            PackageType.CavendoRoadSign,
            PackageType.CavendoTownSign,
            PackageType.CragstoneRoadSign,
            PackageType.CragstoneTownSign,
            PackageType.GurokoraRoadSign,
            PackageType.GurokoraTownSign,
            PackageType.HakataRoadSign,
            PackageType.HakataTownSign,
            PackageType.IkerasRoadSign,
            PackageType.IkerasTownSign,
            PackageType.KehanRoadSign,
            PackageType.KehanTownSign,
            PackageType.KeidelurRoadSign,
            PackageType.KeidelurTownSign,
            PackageType.LinvakTukalRoadSign,
            PackageType.LinvakTukalTownSign,
            PackageType.MayoiRoadSign,
            PackageType.MayoiTownSign,
            PackageType.MillstoneRoadSign,
            PackageType.MillstoneTownSign,
            PackageType.MolwirthRoadSign,
            PackageType.MolwirthTownSign,
            PackageType.OndekodoRoadSign,
            PackageType.OndekodoTownSign,
            PackageType.PalisadeRoadSign,
            PackageType.PalisadeTownSign,
            PackageType.RakaniRoadSign,
            PackageType.RakaniTownSign,
            PackageType.RithwicRoadSign,
            PackageType.RithwicTownSign,
            PackageType.ShinokoRoadSign,
            PackageType.ShinokoTownSign,
            PackageType.ShoushiRoadSign,
            PackageType.ShoushiTownSign,
            PackageType.SignGatewayAriaki,
            PackageType.SignGatewayArwic,
            PackageType.SignGatewayCobalt,
            PackageType.SignGatewayCragstone,
            PackageType.SignGatewayDrudgeCitadel,
            PackageType.SignGatewayEsper,
            PackageType.SignGatewayFarali,
            PackageType.SignGatewayGevoth,
            PackageType.SignGatewayKydi,
            PackageType.SignGatewayLostWish,
            PackageType.SignGatewayLumari,
            PackageType.SignGatewayMadCrone,
            PackageType.SignGatewayMalthabbor,
            PackageType.SignGatewayNaderu,
            PackageType.SignGatewayNepeth,
            PackageType.SignGatewayOriad,
            PackageType.SignGatewayProsper,
            PackageType.SignGatewayStoneshadow,
            PackageType.SignGatewayThusik,
            PackageType.SignGatewayTouTou,
            PackageType.SignGatewayVesayen,
            PackageType.SignGatewayWinterhollows,
            PackageType.SignRoadArwicEastOutpost,
            PackageType.SignRoadArwicNorthOutpost,
            PackageType.SignRoadArwicSouthOutpost,
            PackageType.SignRoadKehanNortheastOutpost,
            PackageType.SignRoadKehanNorthwestOutpost,
            PackageType.SignRoadKehanSoutheastOutpost,
            PackageType.SignRoadMillstoneNortheasternOutpost,
            PackageType.SignRoadMillstoneNorthwesternOutpost,
            PackageType.SignRoadMillstoneSouthwesternOutpost,
            PackageType.WhitebayRoadSign,
            PackageType.WhitebayTownSign,
            PackageType.ZuRoadSign,
            PackageType.ZuTownSign,
        };

        public static readonly HashSet<PackageType> SCEPTER_LUGIAN_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.ScepterLugian,
            PackageType.ScepterLugianAvalanche,
            PackageType.ScepterLugianCrystal,
            PackageType.ScepterLugianImpact,
            PackageType.ScepterLugianResounding,
            PackageType.ScepterLugianStarter,
            PackageType.ScepterUnaro,
            PackageType.SlamstickAvalancheScepterGoldenAge,

            PackageType.SlamstickAvalancheScepterAncients,
            PackageType.SlamstickAvalancheScepterSunBlaze,
        };

        public static readonly HashSet<PackageType> SHARD_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Shard_Cragstone,
        };

        public static readonly HashSet<PackageType> SPEAR_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.SpearTumerokBarbedJavelin,
            PackageType.SpearTumerokHarpoon,
            PackageType.SpearTumerokJavelin,
            PackageType.SpearTumerokPunishingSpear,
            PackageType.SpearTumerokPunishingSpearGoldenAge,
            PackageType.SpearTumerokSkullJavelin,
            PackageType.SpearTumerokSpineJavelin,
            PackageType.SpearTumerokStarter,

            PackageType.SpearTumerokPunishingSpearAncients,
            PackageType.SpearTumerokPunishingSpearSunBlaze,
        };

        public static readonly HashSet<PackageType> STAVE_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.StaffAdept,
            PackageType.StaffApprentice,
            PackageType.StaffArchmage,
            PackageType.StaffBurunImmortal,
            PackageType.StaffBurunKeerik,
            PackageType.StaffBurunPatriarch,
            PackageType.StaffBurunRehir,
            PackageType.StaffGurogDread_VaultBoss,
            PackageType.StaffGurogShaman,
            PackageType.StaffGurogSorcerer,
            PackageType.StaffGurogWarlock,
            PackageType.StaffMagus,
            PackageType.StaffMaster,
            PackageType.StaffMasterGoldenAge,
            PackageType.StaffUnaro,
            PackageType.StaveHumanStarter,
            PackageType.StaveMimbu,
            PackageType.WandMimbuAcita,
            PackageType.WandMimbuAkeha,
            PackageType.WandMimbuAlshan,
            PackageType.WandMimbuCurse,
            PackageType.WandMimbuFeyen,
            PackageType.WandMimbuHinu,
            PackageType.WandMimbuKachem,
            PackageType.WandMimbuTolen,

            PackageType.StaffMasterAncients,
            PackageType.StaffMasterSunBlaze,
        };

        public static readonly HashSet<PackageType> SWORD_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.BoardTemplate,
            PackageType.ClubBanderlingBerserker,
            PackageType.ClubBanderlingBouncer,
            PackageType.ClubBanderlingCrasher,
            PackageType.ClubBanderlingRaver,
            PackageType.ClubBanderlingSlammer,
            PackageType.ClubBanderlingThrasher,
            PackageType.ClubCudgelDrudgeOutcast,
            PackageType.ClubCudgelDrudgeSlinker,
            PackageType.ClubElementalAstyrrian,
            PackageType.ClubElementalInferno,
            PackageType.ClubElementalTsunami,
            PackageType.ClubGruttDustbin,
            PackageType.ClubGruttFilthminder,
            PackageType.ClubGruttMorbific,
            PackageType.ClubGruttMorbificBoar,
            PackageType.ClubGruttPlaguebearer,
            PackageType.ClubGruttPlaguebearerBoar,
            PackageType.ClubGruttSepsis,
            PackageType.ClubMonougaBeastly,
            PackageType.ClubMonougaBrutish,
            PackageType.ClubMonougaMonstrous,
            PackageType.ClubMonougaSavage,
            PackageType.ClubMonougaThuggish,
            PackageType.ClubStoneDrudgeKeeper,
            PackageType.ClubStoneDrudgeProwler,
            PackageType.ClubStoneDrudgeRobber,
            PackageType.ClubStoneDrudgeWarlord,
            PackageType.DaggerScravenHamekh,
            PackageType.DaggerScravenVenar,
            PackageType.DaggerVerminCrawlspace,
            PackageType.DaggerVerminSmugglerKing,
            PackageType.DaggerVerminTanglefoot,
            PackageType.SickleBurunBroodu,
            PackageType.SickleBurunKiree,
            PackageType.SickleBurunKreekunNaderu,
            PackageType.SickleBurunRuruk,
            PackageType.SickleBurunSlavetaker,
            PackageType.SickleVirindiAberrant,
            PackageType.SickleVirindiExecutor,
            PackageType.SickleVirindiGuardian,
            PackageType.SickleVirindiMaster,
            PackageType.SickleVirindiPuppet,
            PackageType.SickleVirindiServitor,
            PackageType.SpearVerminDank,
            PackageType.SpearVerminFilcherGreat,
            PackageType.SpearVerminUsurper,
            PackageType.SwordFlayerDrift,
            PackageType.SwordFlayerSquall,
            PackageType.SwordFlayerStorm,
            PackageType.SwordFlayerTempest,
            PackageType.SwordFlayerWind,
            PackageType.SwordHumanKingsGoldenAge,
            PackageType.SwordHumanLong,
            PackageType.SwordHumanStarter,
            PackageType.SwordKing,
            PackageType.SwordKnight,
            PackageType.SwordLugianBroadsword,
            PackageType.SwordLugianFork,
            PackageType.SwordLugianForkStinging,
            PackageType.SwordLugianGreatStonebones,
            PackageType.SwordLugianGreatsword,
            PackageType.SwordLugianGreatswordGoldenAge,
            PackageType.SwordLugianLevelRestricted,
            PackageType.SwordLugianMorbific,
            PackageType.SwordLugianNeedler,
            PackageType.SwordLugianShort,
            PackageType.SwordLugianStarter,
            PackageType.SwordLugianTalwar,
            PackageType.SwordLugianTalwarQuicksilver,
            PackageType.SwordNoble,
            PackageType.SwordPeasant,
            PackageType.SwordRashanDrudgeBane,
            PackageType.SwordRevenantConscript,
            PackageType.SwordRevenantGaerlan,
            PackageType.SwordRevenantLegionary,
            PackageType.SwordRevenantLictor,
            PackageType.SwordRevenantMagister,
            PackageType.SwordRevenantPraetor,
            PackageType.SwordRevenantPrefect,
            PackageType.SwordRevenantRhetor,
            PackageType.SwordRevenantRytheran,
            PackageType.SwordScraven,
            PackageType.SwordScravenRukh,
            PackageType.SwordScravenRukhSuzerain,
            PackageType.SwordScravenShimar,
            PackageType.SwordScravenTalon,
            PackageType.SwordSquire,
            PackageType.SwordTumerokClawblade,
            PackageType.SwordTumerokHooksword,
            PackageType.SwordTumerokRakeblade,
            PackageType.SwordTumerokStarter,
            PackageType.Torch,
        };

        public static readonly HashSet<PackageType> TOOL_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Athame,
            PackageType.Crucible,
            PackageType.FlatHammer,
            PackageType.MagnifyingGlass,
            PackageType.ShapingHammer,
            PackageType.TestTool,
            PackageType.Tool_Chisel,
            PackageType.Tool_Crucible,
            PackageType.Tool_FlatHammer,
            PackageType.Tool_GreaterChisel,
            PackageType.Tool_GreaterCrucible,
            PackageType.Tool_GreaterFlatHammer,
            PackageType.Tool_GreaterHatchet,
            PackageType.Tool_GreaterMagnifyingGlass,
            PackageType.Tool_GreaterMattock,
            PackageType.Tool_GreaterPickaxe,
            PackageType.Tool_GreaterShapingHammer,
            PackageType.Tool_Hatchet,
            PackageType.Tool_LesserChisel,
            PackageType.Tool_LesserCrucible,
            PackageType.Tool_LesserFlatHammer,
            PackageType.Tool_LesserHatchet,
            PackageType.Tool_LesserMagnifyingGlass,
            PackageType.Tool_LesserMattock,
            PackageType.Tool_LesserPickaxe,
            PackageType.Tool_LesserShapingHammer,
            PackageType.Tool_MagnifyingGlass,
            PackageType.Tool_Mattock,
            PackageType.Tool_Pickaxe,
            PackageType.Tool_ShapingHammer,
        };

        public static readonly HashSet<PackageType> TROPHY_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.AmethystOrder,
            PackageType.BloodTyrantCloud,
            PackageType.BloodTyrantCrag,
            PackageType.BloodTyrantSpindrift,
            PackageType.BloodTyrantSquall,
            PackageType.BloodTyrantStorm,
            PackageType.BurunSlavetakerHead,
            PackageType.CharmRatSmasher,
            PackageType.DarkstoneFaded,
            PackageType.DelvingStone,
            PackageType.DoctrineDominion,
            PackageType.DoctrineOrderOfDereth,
            PackageType.DoctrineShadowKingdom,
            PackageType.DyePlantTemplate,
            PackageType.ElixirBeetleSlayer,
            PackageType.ElixirWaspBane,
            PackageType.EmeraldVakentu,
            PackageType.HeartTyrantLiving,
            PackageType.HeartTyrantStone,
            PackageType.IchorNefaneOpor,
            PackageType.IchorNiffisGlissna,
            PackageType.IchorNiffisListris,
            PackageType.IchorNiffisOpor,
            PackageType.InvisibleItemTemplate,
            PackageType.LearningStone,
            PackageType.Lodestone,
            PackageType.MedallionObsidianBroken,
            PackageType.MedallionObsidianPiece,
            PackageType.MedallionOpening,
            PackageType.MistOpal,
            PackageType.MistOpalCracked,
            PackageType.OilGigurathBehemorn,
            PackageType.PeriaptAncients,
            PackageType.RubyTurmoil,
            PackageType.SealAcademy,
            PackageType.TanachaArmoredilloPiece,
            PackageType.TanachaBeetlePiece,
            PackageType.TanachaReedsharkPiece,
            PackageType.TanachaScravenPiece,
            PackageType.TanachaShrethPiece,
            PackageType.ThighboneRevenantConscript,
            PackageType.ThighboneRevenantLegionary,
            PackageType.ThighboneRevenantPrefect,
            PackageType.ToolDiggingShelter,
            PackageType.TopazJustice,
            PackageType.TrophyArmoredilloSlayerElixir,
            PackageType.TrophyBanderlingBeard,
            PackageType.TrophyBanderlingHeart,
            PackageType.TrophyBanderlingTooth,
            PackageType.TrophyCroneAmulet,
            PackageType.TrophyCroneBottle,
            PackageType.TrophyCroneBroom,
            PackageType.TrophyCroneHorns,
            PackageType.TrophyDarkenfowlEgg,
            PackageType.TrophyDrudgeIdol,
            PackageType.TrophyGearKnightHelm,
            PackageType.TrophyGearKnightPauldron,
            PackageType.TrophyGigurathClaw,
            PackageType.TrophyGigurathHoof,
            PackageType.TrophyGruttLeg,
            PackageType.TrophyGruttTusk,
            PackageType.TrophyMimbuArmor,
            PackageType.TrophyMimbuCarapace,
            PackageType.TrophyMimbuJar,
            PackageType.TrophyMimbuScarab,
            PackageType.TrophyMimbuSkin,
            PackageType.TrophyMoarsmanClaws,
            PackageType.TrophyMoarsmanFins,
            PackageType.TrophyMonougaBone,
            PackageType.TrophyMonougaBones,
            PackageType.TrophyMonougaEyes,
            PackageType.TrophyMonougaGland,
            PackageType.TrophyMonougaSkin,
            PackageType.TrophyNefanePearl,
            PackageType.TrophyNefaneShell,
            PackageType.TrophyPhyntoswaspCarapace,
            PackageType.TrophyPhyntoswaspStinger,
            PackageType.TrophyPhyntoswaspWings,
            PackageType.TrophyReaperHorns,
            PackageType.TrophyReedsharkFin,
            PackageType.TrophyReedsharkPlate,
            PackageType.TrophyReedsharkSkin,
            PackageType.TrophyReedsharkSpike,
            PackageType.TrophySclavusHead,
            PackageType.TrophySclavusSkin,
            PackageType.TrophySclavusTail,
            PackageType.TrophySclavusVenom,
            PackageType.TrophyShrethHair,
            PackageType.TrophyShrethHorns,
            PackageType.TrophySlithisEye,
            PackageType.TrophySlithisScale,
            PackageType.TrophyStatueOrb,
            PackageType.TrophyThornlingEyeball,
            PackageType.TrophyThornlingSap,
            PackageType.TrophyTyrantClaw,
            PackageType.TrophyTyrantEye,
            PackageType.TrophyTyrantScales,
            PackageType.TrophyTyrantTongue,
            PackageType.TrophyTyrantTooth,
        };

        public static readonly HashSet<PackageType> WASPNEST_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.NestStinging,
            PackageType.NestSwarming,
            PackageType.NestTumerokSwarmingGoldenAge,
            PackageType.NestWasp,

            PackageType.NestTumerokSwarmingAncients,
            PackageType.NestTumerokSwarmingSunBlaze,
        };

        public static readonly HashSet<PackageType> WRENCH_TEMPLATE_PACKAGES = new HashSet<PackageType> {
            PackageType.Wrench,
            PackageType.WrenchCreator,
            PackageType.WrenchLugianCreatorsGoldenAge,
            PackageType.WrenchTinker,

            PackageType.WrenchLugianCreatorsAncients,
            PackageType.WrenchLugianCreatorsSunBlaze,
        };
    }
}
