namespace AC2RE.Definitions {

    // Const *_IIDStat
    public enum InstanceIdStat : uint {
        UNDEF = 0,
        WB_RUNTIMEID = 1,
        OWNER = 256,
        VIEWER = 257,
        CONTAINER = 258,
        BONDED = 259,
        FREEZER = 260,
        EQUIPPER = 261,
        VIEWING = 262,
        ATTUNED = 263,
        AUTHOR = 264,
        VENDOR_CURRENT = 275,
        EXPERIENCE_FORWHOM = 280,
        GEN_MANAGER = 300,
        GEN_PERSONALIZATIONTARGET = 301,
        CRAFTER = 302,
        PLUNDERER = 320,
        ORIGINATOR = 321,
        CLAIMANT = 322,
        LAST_USER = 323,
        FELLOWSHIP_RECRUITER = 400,
        ALLEGIANCE_VASSAL = 450,
        ALLEGIANCE_PATRON = 451,
        ALLEGIANCE_MONARCH = 452,
        ALLEGIANCE_PROFILETARGET = 453,
        AI_MASTER = 500,
        AI_PETMASTER = 501,
        AI_PETTARGET = 502,
        AI_FELLOWSHIP = 503,
        AI_ALLEGIANCE = 504,
        AI_PETSUMMONER = 505,
        AI_PETFELLOWSHIPLEADER = 506,
        CURRENTNPCBEINGUSED = 507,
        EFFECT_SUMMONER = 600,
        EFFECT_SUMMONERTARGET = 601,
    }
}
