namespace AC2RE.Definitions {

    // Const *_TSStat
    public enum TimestampStat : uint {
        UNDEF = 0,
        CHECKPOINT = 1,
        ITEMHOUSEKEEPINGDELETETIME = 2,
        LASTDEATHTIME = 256,
        USAGE_LASTUSAGETIME = 300,
        DATAMINER_LOGINTIME = 301,
        LASTATTACKTIME = 302,
        SKILL_TIMELASTRESET = 303,
        SKILL_LASTUNTRAIN = 304,
        COMBAT_LASTCOMBATINTERACTION = 305,
        SKILL_LASTCOMPLETERESET = 306,
        CRAFTSKILL_LASTCOMPLETERESET = 307,
        SKILL_LASTCOMPLETEHERORESET = 308,
        AI_IMPLEMENTCHANGE = 400,
        AI_PETLASTCOMMANDTIME = 401,
        AI_TIMER = 402,
        FACTION_LASTCHANGETIME = 500,
        FACTION_LANDBLOCKLASTCHANGETIME = 501,
        ALLEGIANCE_LASTPROFILESYNC = 600,
        TRADE_LASTOPENTRADE = 700,
        HEARTBEAT_LASTHEARTBEATTIME = 800,
        EXTRASALESUPDATED = 850,
        CREATIONDATE = 900,
    }
}
