namespace AC2RE.Definitions {

    // Dat file 230000FE
    public enum AILoveTableType : uint {

        AIFRIENDTABLE_BURUN = 2,
        AIFRIENDTABLE_CRONE = 3,

        AIFRIENDTABLE_DRUDGE = 6,

        AIFRIENDTABLE_GUROG = 8,
        AIFRIENDTABLE_MIMBU = 9,
        AIFRIENDTABLE_MOARSMAN = 10,

        AIFRIENDTABLE_RABBIT = 14,
        AIFRIENDTABLE_REAPER = 15,

        AIFRIENDTABLE_SCLAVUS = 17,

        AIFRIENDTABLE_FACTIONAL = 20,
        AIFRIENDTABLE_GROUP = 21,
        AIFRIENDTABLE_LONER = 22,
        AIFRIENDTABLE_MUSICIAN = 23,
        AIFRIENDTABLE_PLAYERFRIENDLY = 24,
        AILOVETABLE_DEFAULTPET = 25,
        AILOVETABLE_FACTION = 26,
        AILOVETABLE_PETFACTIONAL = 27,
        AILOVETABLE_PETFACTIONALELEMENTAL = 28,
        AILOVETABLE_PETFACTIONALSHADOW = 29,
        AILOVETABLE_PETFACTIONALVIRINDI = 30,
        AILOVETABLE_TURRETPET = 31,
        AILOVETABLE_TUTORIAL = 32,

        AIFRIENDTABLE_PACIFIST = 35,
        TESTAILOVETABLE_FACTION = 36,
        TESTAILOVETABLE_FACTIONNEUTRAL = 37,
        TESTAILOVETABLE_PLAYERFRIENDLY = 38,
        AIFRIENDTABLE_SHRETHGAUNTLETCLIQUE = 39,
        AIFRIENDTABLE_SKELETONRIDER = 40,

        AIFRIENDTABLE_UNDEAD = 42,
        AIFRIENDTABLE_SKELETON = 43,
        AIFRIENDTABLE_ELIAVENGER = 44,
        AIFRIENDTABLE_SALVATIONNPC = 45,
        AIFRIENDTABLE_MUMIYAH = 46,
        AIFRIENDTABLE_OLTHOI = 47,
        AILOVETABLE_DEFAULTQUESTPET = 48,
        AIFRIENDTABLE_UNDEADARCHON = 49,
        AIFRIENDTABLE_UNDEADLOYALIST = 50,

        AIFRIENDTABLE_WARAERFALLESIDE = 53,
        AIFRIENDTABLE_WARARCHONSIDE = 54,
        AIFRIENDTABLE_PORTALBEACON = 55,
        AIFRIENDTABLE_DRUDGEPEACEFUL = 56,
        AIFRIENDTABLE_CHAOSCCP = 57,

        AIFRIENDTABLE_JAZZBANDHUMAN = 59,
        AIFRIENDTABLE_JAZZBANDLUGIAN = 60,
        AIFRIENDTABLE_JAZZBANDTUMEROK = 61,
        AIFRIENDTABLE_LDDEFENDERS = 62,
        AIFRIENDTABLE_LDRENEGADES = 63,
        AIFRIENDTABLE_COLOSSUS = 64,
        AIFRIENDTABLE_DEFAULTGROUP = 65,
        AIFRIENDTABLE_DEFAULTSOLO = 66,
        AIFRIENDTABLE_FALATACOT = 67,
        AIFRIENDTABLE_GEARLEGIONARY = 68,
        AIFRIENDTABLE_KNORRUNDEAD = 69,
        AIFRIENDTABLE_LIGHTORIENTED = 70,
        AIFRIENDTABLE_SERVITOR = 71,
        AIFRIENDTABLE_SWARMOLTHOI = 72,
        AIFRIENDTABLE_TAKERU = 73,
        AIFRIENDTABLE_SENTRY = 74,
        AIFRIENDTABLE_GEARLEGIONARYASSAULT = 75,
        AIFRIENDTABLE_SWARMTUNNELERLOD = 76,
        AIFRIENDTABLE_GEARLEGIONARYMK2ASSAULT = 77,
        AIFRIENDTABLE_GEARLEGIONARYMK2STRIKE = 78,
        AIFRIENDTABLE_SKYPORTSERVITOR = 79,
        AIFRIENDTABLE_XENOPHOBE = 80,
        AILOVETABLE_MONSTERWILDMAGIC = 81,
        AIFRIENDTABLE_HATER = 82,
        AIFRIENDTABLE_SLITHIS = 83,
    }
}
