namespace AC2RE.Definitions {

    // Dat file 230000DC
    public enum AISuperClass : uint {

        BANDERLING = 2,
        BEETLE = 3,
        CRONE = 4,
        DARKENFOWL = 5,
        DRUDGE = 6,
        HUMANROGUE = 7,
        LUGIANROGUE = 8,
        MIMBU = 9,
        MONOUGA = 10,
        MOSSWART = 11,
        PHYNTOSWASP = 12,
        REEDSHARK = 13,
        SCLAVUS = 14,
        SCRAVEN = 15,
        THORNLING = 16,
        TUMEROKROGUE = 17,
        GRUTT = 18,
        VERMIN = 19,
        TYRANT = 20,
        BURUN = 21,
        GUROG = 22,
        MOARSMAN = 23,

        MUCOR = 25,

        REAPER = 27,
        SPAWN = 28,
        UNDEAD = 29,
        RABBIT = 30,
        ARMOREDILLO = 31,
        GOLEM = 32,
        ELI = 33,
        EROBAL = 34,
        FLAYER = 35,
        GEARKNIGHT = 36,
        GIGURATH = 37,
        ELEMENTAL = 38,
        LASHER = 39,
        OLTHOI = 40,
        SHADOW = 41,
        VIRINDI = 42,

        SHRETH = 44,

        NEFANE = 48,
        NIFFIS = 49,
        GUARDIAN = 50,
        DARKENFOWLGUARD = 51,
        SKELETON = 52,
        SKELETONRIDER = 53,
        DRUDGEOUTCASTKING = 54,
        RYTHERAN = 55,
        ARTEFONUNDEAD = 56,
        WARATH = 57,
        BLOODSTONE = 58,
        SALVATIONNPC = 59,
        CONVERSION_UNDEAD = 60,
        GHOST = 61,
        WARATHEMPOWERED = 62,
        MUMIYAH = 63,
        WISP = 64,
        MOSSWARTPET = 65,
        BOULDER = 66,
        UNDEADARCHON = 67,
        UNDEADLOYALIST = 68,
        UNDEAD_AERFALLE = 69,
        UNDEAD_ARCHON = 70,
        PORTALBEACON = 71,
        RABBITWHITE = 72,
        WISPCHAOSEMPOWERED = 73,
        FISHSCHOOL = 74,
        SPIRIT = 75,
        CHAOTIC = 76,
        SHRETHORG = 77,
        ANCIENTS = 78,
        BLOODLORDS = 79,
        JAZZBANDHUMAN = 80,
        JAZZBANDLUGIAN = 81,
        JAZZBANDTUMEROK = 82,
        RIFT = 83,
        CLUSTER = 84,
        GAUNTLET = 85,
        RENEGADES = 86,
        LIGHTWISPPET = 87,
        LDDEFENDERS = 88,
        ATFANATICS = 89,
        COLOSSUS = 90,
        FALATACOT = 91,
        FELSISTER = 92,
        GEARLEGIONARY = 93,
        GRIEVVER = 94,
        GROMNIE = 95,
        HIGHMUMIYAH = 96,
        HIGHUNDEAD = 97,
        KALLIKAN = 98,
        KNATH = 99,
        LEVENNATH = 100,
        SERVITOR = 101,
        SLITHIS = 102,
        SWARMOLTHOI = 103,
        TAKERU = 104,
        THRALL = 105,
        URKHAD = 106,
        URSUIN = 107,
        SWARMOLTHOIROYALTY = 108,
        GRIEVVERHIGH = 109,
        ENSLAVEDOLTHOI = 110,
        SKYPORTHOSTILE = 111,
        ARCHIVEHOSTILE = 112,
        GEARLEVEL1FOUNDRY = 113,
        LODSUPPORTPILLAR = 114,
        GEARMK2ASSAULT = 115,
        GEARMK2STRIKE = 116,
        SHRETHBASEULTRATURRET = 117,
        CARENZI = 118,
        SWARM = 119,
        SLAVESPAWN = 120,

        PLAYERHUMAN = 65280,
        PLAYERLUGIAN = 65281,
        PLAYERTUMEROK = 65282,
        PET = 65283,
        PETPLAYERHOSTILE = 65284,

        PLAYEREMPYREAN = 65288,

        PLAYERDRUDGE = 65296,

        FRIEND = 65535,
    }
}
