namespace AC2RE.Definitions;

// Enum ChatNetworkBlobType
public enum ChatNetworkBlobType : uint {
    UNKNOWN, // NETBLOB_UNKNOWN
    EVENT_BINARY, // NETBLOB_EVENT_BINARY
    EVENT_XMLRPC, // NETBLOB_EVENT_XMLRPC
    REQUEST_BINARY, // NETBLOB_REQUEST_BINARY
    REQUEST_XMLRPC, // NETBLOB_REQUEST_XMLRPC
    RESPONSE_BINARY, // NETBLOB_RESPONSE_BINARY
    RESPONSE_XMLRPC, // NETBLOB_RESPONSE_XMLRPC
}
