namespace AC2RE.Definitions;

// Enum AsyncMethod::AsyncMethodID
public enum ChatAsyncMethodId : uint {
    UNKNOWN, // ASYNCMETHOD_UNKNOWN
    SEND_TO_ROOM_BY_NAME, // ASYNCMETHOD_SENDTOROOMBYNAME
    SEND_TO_ROOM_BY_ID, // ASYNCMETHOD_SENDTOROOMBYID
    CREATE_ROOM, // ASYNCMETHOD_CREATEROOM
    INVITE_CLIENT_TO_ROOM_BY_ID, // ASYNCMETHOD_INVITECLIENTTOROOMBYID
    EJECT_CLIENT_FROM_ROOM_BY_ID, // ASYNCMETHOD_EJECTCLIENTFROMROOMBYID
}
