namespace AC2RE.Definitions;

// Enum charError
public enum CharError : uint {
    UNDEF, // CHAR_ERROR_UNDEF
    LOGGED_ON, // CHAR_ERROR_LOGGED_ON
    ACCOUNT_LOGON, // CHAR_ERROR_ACCOUNT_LOGON
    SERVER_CRASH, // CHAR_ERROR_SERVER_CRASH
    LOGOFF, // CHAR_ERROR_LOGOFF
    DELETE, // CHAR_ERROR_DELETE
    ACCOUNT_IN_USE, // CHAR_ERROR_ACCOUNT_IN_USE
    ACCOUNT_INVALID, // CHAR_ERROR_ACCOUNT_INVALID
    ACCOUNT_DOESNT_EXIST, // CHAR_ERROR_ACCOUNT_DOESNT_EXIST
    ENTER_GAME_GENERIC, // CHAR_ERROR_ENTER_GAME_GENERIC
    ENTER_GAME_STRESS_ACCOUNT, // CHAR_ERROR_ENTER_GAME_STRESS_ACCOUNT
    ENTER_GAME_CHARACTER_IN_WORLD, // CHAR_ERROR_ENTER_GAME_CHARACTER_IN_WORLD
    ENTER_GAME_PLAYER_ACCOUNT_MISSING, // CHAR_ERROR_ENTER_GAME_PLAYER_ACCOUNT_MISSING
    ENTER_GAME_CHARACTER_NOT_OWNED, // CHAR_ERROR_ENTER_GAME_CHARACTER_NOT_OWNED
    ENTER_GAME_CHARACTER_IN_WORLD_SERVER, // CHAR_ERROR_ENTER_GAME_CHARACTER_IN_WORLD_SERVER
    ENTER_GAME_OLD_CHARACTER, // CHAR_ERROR_ENTER_GAME_OLD_CHARACTER
    ENTER_GAME_CORRUPT_CHARACTER, // CHAR_ERROR_ENTER_GAME_CORRUPT_CHARACTER
    ENTER_GAME_START_SERVER_DOWN, // CHAR_ERROR_ENTER_GAME_START_SERVER_DOWN
    ENTER_GAME_COULDNT_PLACE_CHARACTER, // CHAR_ERROR_ENTER_GAME_COULDNT_PLACE_CHARACTER
    LOGON_SERVER_FULL, // CHAR_ERROR_LOGON_SERVER_FULL
    CHARACTER_IS_BOOTED, // CHAR_ERROR_CHARACTER_IS_BOOTED
    ENTER_GAME_CHARACTER_LOCKED, // CHAR_ERROR_ENTER_GAME_CHARACTER_LOCKED
}
