namespace AC2RE.Definitions {

    // Enum charError
    public enum CharError : uint {
        UNDEF,
        LOGGED_ON,
        ACCOUNT_LOGON,
        SERVER_CRASH,
        LOGOFF,
        DELETE,
        ACCOUNT_IN_USE,
        ACCOUNT_INVALID,
        ACCOUNT_DOESNT_EXIST,
        ENTER_GAME_GENERIC,
        ENTER_GAME_STRESS_ACCOUNT,
        ENTER_GAME_CHARACTER_IN_WORLD,
        ENTER_GAME_PLAYER_ACCOUNT_MISSING,
        ENTER_GAME_CHARACTER_NOT_OWNED,
        ENTER_GAME_CHARACTER_IN_WORLD_SERVER,
        ENTER_GAME_OLD_CHARACTER,
        ENTER_GAME_CORRUPT_CHARACTER,
        ENTER_GAME_START_SERVER_DOWN,
        ENTER_GAME_COULDNT_PLACE_CHARACTER,
        LOGON_SERVER_FULL,
        CHARACTER_IS_BOOTED,
        ENTER_GAME_CHARACTER_LOCKED,
    }
}
