using System.Collections.Generic;

namespace AC2RE.Definitions {

    public class PropertyMapper : IPackage {

        // Property stat mappings from WSL func gmPropertyMapper::constructor
        public static readonly Dictionary<PropertyName, BoolStat> PROPERTY_NAME_TO_BOOL_STAT = new() {
            { PropertyName.NEVERHOUSEKEEP, BoolStat.NEVERHOUSEKEEP },
            { PropertyName.GENERATORNONPERSONALIZABLE, BoolStat.GEN_NONPERSONALIZABLE },
            { PropertyName.GENERATORREGENALLIFUNBOUND, BoolStat.GEN_REGENALLIFUNBOUND },
            { PropertyName.GENERATORENTERWORLDPRESERVE, BoolStat.GEN_ENTERWORLDPRESERVE },
            { PropertyName.GENERATORMUNGE, BoolStat.GEN_MUNGE },
            { PropertyName.GENERATORDONTMUNGE, BoolStat.GEN_DONTMUNGE },
            { PropertyName.GENERATORABSOLUTEQUANTITY, BoolStat.GEN_ABSOLUTEQUANTITY },
            { PropertyName.GENERATORCHECKPOINT, BoolStat.GEN_CHECKPOINT },
            { PropertyName.GENERATORDONTCHECKPOINT, BoolStat.GEN_DONTCHECKPOINT },
            { PropertyName.ITEM_ISSTACKABLE, BoolStat.STACKABLE },
            { PropertyName.ITEM_CANUSEWHILEMOVING, BoolStat.USAGE_USEWHILEMOVING },
            { PropertyName.ITEM_CANUSEONLYININVENTORY, BoolStat.USAGE_INVENTORYREQUIRED },
            { PropertyName.ITEM_CANUSEWHENCOLLIDED, BoolStat.USAGE_USEWHENCOLLIDED },
            { PropertyName.ITEM_ISLOCKONUSE, BoolStat.USAGE_LOCKONUSE },
            { PropertyName.ITEM_ISATTUNABLE, BoolStat.ATTUNABLE },
            { PropertyName.ITEM_ISUSABLE, BoolStat.ISUSABLE },
            { PropertyName.ITEM_ISSELECTABLE, BoolStat.ISSELECTABLE },
            { PropertyName.ITEM_ISTAKEABLE, BoolStat.ISTAKEABLE },
            { PropertyName.ITEM_ISDESTROYONUSE, BoolStat.USAGE_DESTROYONUSE },
            { PropertyName.NPC_AREALLITEMSDESTROYEDONROT, BoolStat.DESTROYALLITEMSONROT },
            { PropertyName.NPC_ISLOOTPROOF, BoolStat.LOOTPROOF },
            { PropertyName.USAGE_NONALLEGIANCEONLY, BoolStat.USAGE_NONALLEGIANCEONLY },
            { PropertyName.USAGE_MONARCHONLY, BoolStat.USAGE_MONARCHONLY },
            { PropertyName.USAGE_LANDBLOCKFACTIONREQUIRED, BoolStat.USAGE_LANDBLOCKFACTIONREQUIRED },
            { PropertyName.LOCK_LOCKABLE, BoolStat.USAGE_LOCKABLE },
            { PropertyName.LOCK_OPENONUNLOCK, BoolStat.USAGE_OPENONUNLOCK },
            { PropertyName.LOCK_LOCKONCLOSE, BoolStat.USAGE_LOCKONCLOSE },
            { PropertyName.LOCK_AICANIGNORELOCK, BoolStat.USAGE_AICANIGNORELOCK },
            { PropertyName.AI_CANJOINCLIQUES, BoolStat.AI_CANJOINCLIQUES },
            { PropertyName.AI_FACTIONMEMBERSHIPBASEDONLANDBLOCK, BoolStat.AI_FACTIONBASEDONLANDBLOCK },
            { PropertyName.AI_FACTIONOWNERSHIPCHANGEONDEATH, BoolStat.AI_FACTIONOWNERSHIPBASEDONDEATH },
            { PropertyName.AI_FREEATTACKING, BoolStat.AI_FREEATTACKING },
            { PropertyName.AICOMBAT_WIELDIMPLEMENTS, BoolStat.AI_WIELDIMPLEMENTS },
            { PropertyName.AICOMBAT_USEWEAPONANDSHIELD, BoolStat.AI_WEAPONANDSHIELD },
            { PropertyName.AICOMBAT_CANDUALWIELD, BoolStat.AI_DUALWIELD },
            { PropertyName.AICOMBAT_CANWIELDTWOHANDED, BoolStat.AI_WIELDTWOHANDED },
            { PropertyName.LOCK_ISLOCKED, BoolStat.USAGE_LOCKED },
            { PropertyName.WEAPON_HARMLESS, BoolStat.WEAPON_HARMLESS },
            { PropertyName.AI_WANDERING, BoolStat.AI_WANDERING },
            { PropertyName.AI_CANUSEDOORS, BoolStat.USAGE_AICANUSEDOORS },
            { PropertyName.AI_DETECTIONSPHERES, BoolStat.AI_HASDETECTIONSPHERES },
            { PropertyName.NPC_UNLOCKEDAFTERFIRSTLOOT, BoolStat.UNLOCKAFTERFIRSTLOOT },
            { PropertyName.PLACEABLE, BoolStat.PLACEABLE },
            { PropertyName.NPC_ISGROUPMONSTER, BoolStat.AI_GROUPMONSTER },
            { PropertyName.CONTAINER_CONTAINEDWAITON, BoolStat.GEN_CONTAINEDWAITONOPEN },
            { PropertyName.CONTAINER_MANAGEDGENERATOR, BoolStat.GEN_MANAGED },
            { PropertyName.ITEM_GENINTERNAL, BoolStat.GEN_INTERNAL },
            { PropertyName.ITEM_GENISAGENERATOR, BoolStat.GEN_ISAGENERATOR },
            { PropertyName.MOBILE, BoolStat.ISMOBILE },
            { PropertyName.IGNORECOLLISIONS, BoolStat.IGNORECOLLISIONS },
            { PropertyName.REPORTCOLLISIONS, BoolStat.REPORTCOLLISIONS },
            { PropertyName.AI_CHAMPIONMONSTER, BoolStat.AI_CHAMPIONMONSTER },
            { PropertyName.AI_UNIQUEMONSTER, BoolStat.AI_UNIQUEMONSTER },
            { PropertyName.AI_SPECIALEFFECTMONSTER, BoolStat.AI_SPECIALEFFECTMONSTER },
            { PropertyName.AI_QUESTMONSTER, BoolStat.AI_QUESTMONSTER },
            { PropertyName.AI_UNWIELDITEMSONIDLE, BoolStat.AI_UNWIELDITEMSONIDLE },
            { PropertyName.ITEM_ISQUESTITEM, BoolStat.ISQUESTITEM },
            { PropertyName.CONTAINER_ISACCEPTINGITEMS, BoolStat.OPEN },
            { PropertyName.USAGE_CRAFTERONLY, BoolStat.USAGE_CRAFTERONLY },
            { PropertyName.AI_NEVERSAYDIE, BoolStat.DEATH_NEVERSAYDIE },
            { PropertyName.ITEM_ISRAREITEM, BoolStat.ISRAREITEM },
            { PropertyName.NPC_NEVERLEAVECORPSE, BoolStat.DEATH_NEVERLEAVECORPSE },
            { PropertyName.USAGE_HEROONLY, BoolStat.USAGE_HEROONLY },
            { PropertyName.USAGE_SHOULDUNLOCKUSERFORUSAGEEFFECTS, BoolStat.USAGE_SHOULDUNLOCKUSERFORUSAGEEFFECTS },
            { PropertyName.USAGE_CANCELSAFEMODEONUSAGE, BoolStat.USAGE_CANCELSLIFESTONEPROTECTION },
            { PropertyName.USAGE_SUMMONERONLY, BoolStat.USAGE_SUMMONERONLY },
            { PropertyName.ITEM_ISEXTRACTABLE, BoolStat.ISEXTRACTABLE },
            { PropertyName.USAGE_DURABILITYLOSTONUSE, BoolStat.USAGE_DURABILITYLOSTONUSE },
            { PropertyName.BOOK_SHOWCONTROLS, BoolStat.BOOK_SHOWCONTROLS },
            { PropertyName.USAGE_ISBINDONUSE, BoolStat.USAGE_ISBINDONUSE },
            { PropertyName.USAGE_LEGIONSEXPANSIONONLY, BoolStat.USAGE_LEGIONSEXPANSIONONLY },
            { PropertyName.NPC_DEATHLOOTABSOLUTEOVERRIDE, BoolStat.DEATH_LOOTABSOLUTEOVERRIDE },
            { PropertyName.NPC_MUNGECORPSEOVERRIDEENTITY, BoolStat.NPC_MUNGECORPSEOVERRIDEENTITY },
            { PropertyName.ITEM_ISDAMAGEMODMUTABLE, BoolStat.ITEM_ISDAMAGEMODMUTABLE },
            { PropertyName.AICOMBAT_MELEENPC, BoolStat.AICOMBAT_MELEENPC },
            { PropertyName.AICOMBAT_MISSILENPC, BoolStat.AICOMBAT_MISSILENPC },
            { PropertyName.NPC_NEVERDROPTESSERAE, BoolStat.NPC_NEVERDROPTESSERAE },
            { PropertyName.NPC_NEVERDROPLODESTONES, BoolStat.NPC_NEVERDROPLODESTONES },
        };

        public static readonly Dictionary<PropertyName, DataIdStat> PROPERTY_NAME_TO_DATA_ID_STAT = new() {
            { PropertyName.ICON, DataIdStat.ICONID },
            { PropertyName.PHYSOBJ, DataIdStat.PHYSOBJ },
            { PropertyName.ITEM_PILEAPPEARANCE, DataIdStat.PILEAPPEARANCEID },
            { PropertyName.USAGE_ITEMINTERACTIONTABLE, DataIdStat.USAGE_ITEMINTERACTIONTABLEID },
            { PropertyName.USAGE_ERRORMESSAGESTABLEID, DataIdStat.USAGE_ERRORMESSAGESTABLEID },
            { PropertyName.USAGE_REQUIREDCRAFTSKILL, DataIdStat.USAGE_REQUIREDCRAFTSKILL },
            { PropertyName.FORGEEFFECT, DataIdStat.CRAFT_FORGEEFFECT },
            { PropertyName.MINE_REQUIREDEFFECT, DataIdStat.MINEREQUIREDEFFECT },
            { PropertyName.CRAFTSKILL, DataIdStat.CRAFTSKILL },
            { PropertyName.MINE_OBJECT, DataIdStat.MINEOBJECT },
            { PropertyName.BUTCHERYPROFILE, DataIdStat.BUTCHERYPROFILE },
            { PropertyName.STORETEMPLATE, DataIdStat.STORETEMPLATE },
            { PropertyName.BOOK_IMAGE, DataIdStat.BOOK_IMAGE },
            { PropertyName.STOREGROUP, DataIdStat.STOREGROUP },
            { PropertyName.NPC_CORPSEOVERRIDEENTITY, DataIdStat.NPC_CORPSEOVERRIDEENTITY },
        };

        public static readonly Dictionary<PropertyName, FloatStat> PROPERTY_NAME_TO_FLOAT_STAT = new() {
            { PropertyName.PHYSICS_VELSCALE, FloatStat.PHYSICS_VELSCALE },
            { PropertyName.PHYSICS_ACCSCALE, FloatStat.PHYSICS_ACCSCALE },
            { PropertyName.PHYSICS_COMBATANIMSCALE, FloatStat.PHYSICS_COMBATANIMSCALE },
            { PropertyName.PHYSICS_JUMPSCALE, FloatStat.PHYSICS_JUMPSCALE },
            { PropertyName.GENERATORREGENPERIOD, FloatStat.GEN_REGENINTERVAL },
            { PropertyName.GENERATORINITIALDELAY, FloatStat.GENERATORINITIALDELAY },
            { PropertyName.ITEM_MINUSEDIST, FloatStat.USAGE_MINUSAGEDIST },
            { PropertyName.ITEM_TIMEBETWEENUSES, FloatStat.USAGE_USAGEINTERVAL },
            { PropertyName.NPC_LOOTTIMER, FloatStat.LOOTTIMER },
            { PropertyName.NPC_BASEROTTIME, FloatStat.BASEROTTIME },
            { PropertyName.NPC_MAXACCELERATEDROTTIME, FloatStat.MAXACCELROTTIME },
            { PropertyName.NPC_MINACCELERATEDROTTIME, FloatStat.MINACCELROTTIME },
            { PropertyName.GAMEPLAYSTATISTICS_HEALTHREGENRATE, FloatStat.HEALTH_REGENRATE },
            { PropertyName.GAMEPLAYSTATISTICS_VIGORREGENRATE, FloatStat.VIGOR_REGENRATE },
            { PropertyName.AI_HOMESICKRADIUS, FloatStat.AI_HOMESICKRADIUS },
            { PropertyName.AI_PERCEPTIONRADIUS, FloatStat.AI_PERCEPTIONRADIUS },
            { PropertyName.AICOMBAT_NATURALVARIANCE, FloatStat.WEAPON_VARIANCE },
            { PropertyName.RESETINTERVAL, FloatStat.RESETCOUNTDOWNTIME },
            { PropertyName.WEAPON_VARIANCE, FloatStat.WEAPON_VARIANCE },
            { PropertyName.AI_WANDERINGRANGE, FloatStat.AI_WANDERINGRANGE },
            { PropertyName.AI_WANDERINGPROB, FloatStat.AI_WANDERINGPROB },
            { PropertyName.SCALE, FloatStat.PHYSICS_SCALE },
            { PropertyName.ITEM_MINPERMISSIONCHECKDIST, FloatStat.USAGE_MINPERMISSIONCHECKDIST },
            { PropertyName.MOVEITEMDISTANCE, FloatStat.MOVEITEMDISTANCE },
            { PropertyName.USAGE_USERANIMATIONTIMESCALE, FloatStat.USAGE_USERBEHAVIORTIMESCALE },
            { PropertyName.GAMEPLAYSTATISTICS_COMBATHEALTHREGENRATE, FloatStat.HEALTH_COMBATREGENRATE },
            { PropertyName.GAMEPLAYSTATISTICS_COMBATVIGORREGENRATE, FloatStat.VIGOR_COMBATREGENRATE },
            { PropertyName.WEAPON_CRITICALHITMOD, FloatStat.CRITICALHITMOD },
            { PropertyName.APPEARANCEMUTATIONKEYVALUE, FloatStat.APPEARANCEMUTATIONKEYVALUE },
            { PropertyName.ITEM_DURABILITY_DECAYMOD, FloatStat.DURABILITY_DECAYMOD },
            { PropertyName.USAGE_REQUIREDLOCATIONRADIUS, FloatStat.USAGE_REQUIREDLOCATIONRADIUS },
            { PropertyName.USAGE_REQUIREDLOCATIONCLOSEPROXIMITYMSGRADIUS, FloatStat.USAGE_REQUIREDLOCATIONCLOSEPROXIMITYMSGRADIUS },
            { PropertyName.USAGE_REQUIREDLOCATIONMEDIUMPROXIMITYMSGRADIUS, FloatStat.USAGE_REQUIREDLOCATIONMEDIUMPROXIMITYMSGRADIUS },
            { PropertyName.USAGE_REQUIREDLOCATIONFARPROXIMITYMSGRADIUS, FloatStat.USAGE_REQUIREDLOCATIONFARPROXIMITYMSGRADIUS },
            { PropertyName.USAGE_REQUIREDLOCATIONVERYFARPROXIMITYMSGRADIUS, FloatStat.USAGE_REQUIREDLOCATIONVERYFARPROXIMITYMSGRADIUS },
            { PropertyName.USAGE_DURATION, FloatStat.USAGE_USAGEDURATION },
            { PropertyName.FORGEEFFECTRADIUS, FloatStat.CRAFT_FORGEEFFECTRADIUS },
            { PropertyName.MINE_OBJECTQUANTITYVARIANCE, FloatStat.CRAFT_MINEOBJECTQUANTITYVARIANCE },
            { PropertyName.AI_HEALTHWARNINGLEVEL, FloatStat.AI_HEALTHWARNINGLEVEL },
            { PropertyName.AI_HEALTHAGGRESSIVENESS, FloatStat.AI_HEALTHAGGRESSIVENESS },
            { PropertyName.AI_VIGORWARNINGLEVEL, FloatStat.AI_VIGORWARNINGLEVEL },
            { PropertyName.AI_VIGORAGGRESSIVENESS, FloatStat.AI_VIGORAGGRESSIVENESS },
            { PropertyName.CRAFT_TOOL_XPMOD, FloatStat.CRAFT_TOOLXPMOD },
            { PropertyName.CRAFT_TOOL_QUANTITYMOD, FloatStat.CRAFT_TOOLQUANTITYMOD },
            { PropertyName.CRAFT_DYEPLANT_MOD, FloatStat.CRAFT_DYEPLANTMOD },
            { PropertyName.NPC_BYPASSABLEARMORMOD, FloatStat.BYPASSABLEARMORMOD },
            { PropertyName.NPC_COMBATSPEEDRESISTANCE, FloatStat.COMBATSPEEDRESISTANCE },
            { PropertyName.AI_NEARDEATHLEVEL, FloatStat.AI_NEARDEATHLEVEL },
            { PropertyName.AICOMBAT_TARGETCONSIDERINTERVAL, FloatStat.AICOMBAT_TARGETCONSIDERINTERVAL },
            { PropertyName.NPC_ARMORTHRESHOLD, FloatStat.NPC_ARMORTHRESHOLD },
            { PropertyName.NPC_DAMAGETYPEMOD, FloatStat.NPC_DAMAGETYPEMOD },
            { PropertyName.ITEM_NATUREDAMAGEMOD, FloatStat.ITEM_NATUREDAMAGEMOD },
            { PropertyName.ITEM_DECAYDAMAGEMOD, FloatStat.ITEM_DECAYDAMAGEMOD },
            { PropertyName.ITEM_MARTIALDAMAGEMOD, FloatStat.ITEM_MARTIALDAMAGEMOD },
            { PropertyName.ITEM_ARCANEDAMAGEMOD, FloatStat.ITEM_ARCANEDAMAGEMOD },
            { PropertyName.ITEM_NATUREDAMAGEMODCAP, FloatStat.ITEM_NATUREDAMAGEMODCAP },
            { PropertyName.ITEM_DECAYDAMAGEMODCAP, FloatStat.ITEM_DECAYDAMAGEMODCAP },
            { PropertyName.ITEM_MARTIALDAMAGEMODCAP, FloatStat.ITEM_MARTIALDAMAGEMODCAP },
            { PropertyName.ITEM_ARCANEDAMAGEMODCAP, FloatStat.ITEM_ARCANEDAMAGEMODCAP },
            { PropertyName.ITEM_NATUREDAMAGEMODGROWTHRATE, FloatStat.ITEM_NATUREDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_DECAYDAMAGEMODGROWTHRATE, FloatStat.ITEM_DECAYDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_MARTIALDAMAGEMODGROWTHRATE, FloatStat.ITEM_MARTIALDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_ARCANEDAMAGEMODGROWTHRATE, FloatStat.ITEM_ARCANEDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_NATUREDAMAGEMODBASEMUTABILITYCHANCE, FloatStat.ITEM_NATUREDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_DECAYDAMAGEMODBASEMUTABILITYCHANCE, FloatStat.ITEM_DECAYDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_MARTIALDAMAGEMODBASEMUTABILITYCHANCE, FloatStat.ITEM_MARTIALDAMAGEMODGROWTHRATE },
            { PropertyName.ITEM_ARCANEDAMAGEMODBASEMUTABILITYCHANCE, FloatStat.ITEM_ARCANEDAMAGEMODGROWTHRATE },
            { PropertyName.AI_HARVESTINGVARIANCE, FloatStat.AI_HARVESTINGVARIANCE },
        };

        public static readonly Dictionary<PropertyName, IntStat> PROPERTY_NAME_TO_INT_STAT = new() {
            { PropertyName.USAGE_MINLEVEL, IntStat.USAGE_MINLEVEL },
            { PropertyName.USAGE_MAXLEVEL, IntStat.USAGE_MAXLEVEL },
            { PropertyName.GENERATORPROFILE, IntStat.GEN_PROFILE },
            { PropertyName.GENERATORMINQUANTITYOVERRIDE, IntStat.GEN_MINQUANTITYOVERRIDE },
            { PropertyName.GENERATORMAXQUANTITYOVERRIDE, IntStat.GEN_MAXQUANTITYOVERRIDE },
            { PropertyName.ITEM_MAXSTACKSIZE, IntStat.MAXSTACKSIZE },
            { PropertyName.ITEM_PREFERREDINVENTORYLOCATION, IntStat.PREFERREDINVENTORYLOCATION },
            { PropertyName.ITEM_VALIDINVENTORYLOCATIONS, IntStat.VALIDINVENTORYLOCATIONS },
            { PropertyName.ITEM_PRECLUDEDINVENTORYLOCATIONS, IntStat.PRECLUDEDINVENTORYLOCATIONS },
            { PropertyName.ITEM_PRIMARYPARENTINGLOCATION, IntStat.INV_PRIMARYPARENTINGLOCATION },
            { PropertyName.ITEM_SECONDARYPARENTINGLOCATION, IntStat.INV_SECONDARYPARENTINGLOCATION },
            { PropertyName.ITEM_IMPLEMENTTYPE, IntStat.IMPLEMENTTYPE },
            { PropertyName.ITEM_VALUE, IntStat.VALUE },
            { PropertyName.ITEM_ARMORLEVEL, IntStat.ARMORLEVEL },
            { PropertyName.ITEM_COMBATDELAY, IntStat.COMBATDELAY },
            { PropertyName.ITEM_VALIDTARGETTYPES, IntStat.USAGE_VALIDTARGETTYPES },
            { PropertyName.NPC_ARMORLEVEL, IntStat.NATURALARMOR },
            { PropertyName.NPC_CHALLENGELEVEL, IntStat.CHALLENGELEVEL },
            { PropertyName.USAGE_REQUIREDFACTION, IntStat.USAGE_REQUIREDFACTION },
            { PropertyName.USAGE_REQUIREDRACE, IntStat.USAGE_REQUIREDRACE },
            { PropertyName.USAGE_REQUIREDQUEST, IntStat.USAGE_REQUIREDQUEST },
            { PropertyName.USAGE_REQUIREDQUESTSTATUS, IntStat.USAGE_REQUIREDQUESTSTATUS },
            { PropertyName.USAGE_REQUIREDSKILL1, IntStat.USAGE_REQUIREDSKILL1 },
            { PropertyName.USAGE_REQUIREDSKILL2, IntStat.USAGE_REQUIREDSKILL2 },
            { PropertyName.USAGE_RESTRICTEDSKILL1, IntStat.USAGE_RESTRICTEDSKILL1 },
            { PropertyName.USAGE_RESTRICTEDSKILL2, IntStat.USAGE_RESTRICTEDSKILL2 },
            { PropertyName.USAGE_MINRANK, IntStat.USAGE_MINIMUMRANK },
            { PropertyName.USAGE_MAXRANK, IntStat.USAGE_MAXIMUMRANK },
            { PropertyName.LOCK_KEYID, IntStat.USAGE_KEYID },
            { PropertyName.QUEST_BESTOWEDSCENEID, IntStat.QUEST_BESTOWEDSCENEID },
            { PropertyName.GAMEPLAYSTATISTICS_MAXHEALTH, IntStat.HEALTH_RAWLEVEL },
            { PropertyName.GAMEPLAYSTATISTICS_MAXVIGOR, IntStat.VIGOR_RAWLEVEL },
            { PropertyName.GAMEPLAYSTATISTICS_LEVEL, IntStat.LEVEL },
            { PropertyName.AI_MOVEMENTTYPE, IntStat.AI_MOVEMENTTYPE },
            { PropertyName.AI_FACTIONMEMBERSHIP, IntStat.FACTION_MEMBERSHIP },
            { PropertyName.AICOMBAT_NATURALDAMAGE, IntStat.WEAPON_DAMAGE },
            { PropertyName.AICOMBAT_NATURALVIGORCOST, IntStat.VIGORCOST },
            { PropertyName.AICOMBAT_NATURALWEAPONTIME, IntStat.WEAPON_SPEED },
            { PropertyName.AICOMBAT_NATURALOFFENSEMODIFIER, IntStat.WEAPON_OFFENSEMOD },
            { PropertyName.PORTALFLAGS, IntStat.TRAVEL_PORTALFLAGS },
            { PropertyName.MAXIMUMUPKEEPPOINTS, IntStat.MAXUPKEEPPOINTS },
            { PropertyName.WEAPON_DAMAGE, IntStat.WEAPON_DAMAGE },
            { PropertyName.WEAPON_VIGORCOST, IntStat.VIGORCOST },
            { PropertyName.WEAPON_SPEED, IntStat.WEAPON_SPEED },
            { PropertyName.WEAPON_OFFENSEMOD, IntStat.WEAPON_OFFENSEMOD },
            { PropertyName.WEAPON_SINGLEWEAPONSTANCE, IntStat.WEAPON_SINGLEWEAPONSTANCE },
            { PropertyName.WEAPON_WITHSHIELDSTANCE, IntStat.WEAPON_WITHSHIELDSTANCE },
            { PropertyName.WEAPON_DUALWIELDSTANCE, IntStat.WEAPON_DUALWIELDSTANCE },
            { PropertyName.AI_AISUBCLASS, IntStat.AI_SUBCLASS },
            { PropertyName.AI_AISUPERCLASS, IntStat.AI_SUPERCLASS },
            { PropertyName.NPC_DEATHLOOTPROFILE, IntStat.DEATH_LOOTPROFILE },
            { PropertyName.NPC_GROOVELEVEL, IntStat.GROOVELEVEL },
            { PropertyName.NPC_TSYSCOARSEITEMCLASS, IntStat.TSYS_COARSEITEMCLASS },
            { PropertyName.NPC_TSYSFINEITEMCLASS, IntStat.TSYS_FINEITEMCLASS },
            { PropertyName.ITEM_PARENTINGORIENTATION, IntStat.PARENTINGORIENTATION },
            { PropertyName.CONTAINER_MAXCONTAINERSIZE, IntStat.CONTAINERMAXCAPACITY },
            { PropertyName.CONTAINER_MAXITEMS, IntStat.GEN_MAXQUANTITYOVERRIDE },
            { PropertyName.ITEM_QUANTITY, IntStat.QUANTITY },
            { PropertyName.ITEM_TSYSCOARSEITEMCLASS, IntStat.TSYS_COARSEITEMCLASS },
            { PropertyName.ITEM_TSYSFINEITEMCLASS, IntStat.TSYS_FINEITEMCLASS },
            { PropertyName.ITEM_USAGEANIMATION, IntStat.USAGE_BEHAVIORNAME },
            { PropertyName.ITEM_USAGETARGETTYPE, IntStat.USAGE_TARGETTYPE },
            { PropertyName.ITEM_MAXINSCRIPTIONLENGTH, IntStat.MAXINSCRIPTIONLENGTH },
            { PropertyName.USAGE_ALLOWEDRACES, IntStat.USAGE_REQUIREDRACE },
            { PropertyName.USAGE_REQUIREDQUEST_FORTAKING, IntStat.USAGE_REQUIREDQUEST_TAKE },
            { PropertyName.USAGE_REQUIREDQUESTSTATUS_FORTAKING, IntStat.USAGE_REQUIREDQUESTSTATUS_TAKE },
            { PropertyName.GENERATORQUALITYOVERRIDE, IntStat.GEN_QUALITYOVERRIDE },
            { PropertyName.GENERATORQUALITYVARIANCEOVERRIDE, IntStat.GEN_QUALITYVARIANCEOVERRIDE },
            { PropertyName.NPC_DEATHLOOTQUALITYOVERRIDE, IntStat.DEATH_LOOTQUALITYOVERRIDE },
            { PropertyName.NPC_DEATHLOOTQUALITYVARIANCEOVERRIDE, IntStat.DEATH_LOOTQUALITYVARIANCEOVERRIDE },
            { PropertyName.USAGE_ANIMATION, IntStat.USAGE_BEHAVIORNAME },
            { PropertyName.USAGE_USERANIMATION, IntStat.USAGE_USERBEHAVIORNAME },
            { PropertyName.GENERATOREXITWORLDBEHAVIOR, IntStat.GEN_EXITWORLDBEHAVIOR },
            { PropertyName.GENERATORTOGGLESTATEGAMEEVENT, IntStat.GEN_TOGGLEGAMEEVENT },
            { PropertyName.ITEM_INSCRIBEPERMISSION, IntStat.INSCRIBEPERMISSION },
            { PropertyName.ENTERWORLDFX, IntStat.ENTERWORLDFX },
            { PropertyName.RADARBLIP, IntStat.RADARBLIP },
            { PropertyName.ITEM_CRAFTFLAGS, IntStat.CRAFT_FLAGS },
            { PropertyName.WEAPON_FOCUSCOST, IntStat.FOCUSCOST },
            { PropertyName.GAMEPLAYSTATISTICS_DEATHFOCUS, IntStat.DEATHFOCUS },
            { PropertyName.USAGE_REQUIREDARCANELORE, IntStat.USAGE_REQUIREDARCANELORE },
            { PropertyName.APPEARANCEMUTATIONKEY, IntStat.APPEARANCEMUTATIONKEY },
            { PropertyName.NPC_SKILLTARGETFLAGS, IntStat.SKILLTARGETFLAGS },
            { PropertyName.ITEM_DURABILITY_MAXLEVEL, IntStat.DURABILITY_MAXLEVEL },
            { PropertyName.USAGE_REQUIREDLOCATIONFEEDBACKTYPE, IntStat.USAGE_REQUIREDLOCATIONFEEDBACKTYPE },
            { PropertyName.USAGE_REQUIREDCRAFTSKILLRATING, IntStat.USAGE_REQUIREDCRAFTSKILLRATING },
            { PropertyName.MINE_OBJECTQUANTITY, IntStat.CRAFT_MINEOBJECTQUANTITY },
            { PropertyName.MINE_MAXUSES, IntStat.CRAFT_MINEMAXUSES },
            { PropertyName.MINE_USAGERESETTIME, IntStat.CRAFT_MINEUSAGERESETTIME },
            { PropertyName.ITEM_SLOTS, IntStat.SLOTS },
            { PropertyName.ITEM_DURABILITY_CURRENTLEVEL, IntStat.DURABILITY_CURRENTLEVEL },
            { PropertyName.CRAFT_TOOL_CRAFTSKILLMOD, IntStat.CRAFT_TOOLCRAFTSKILLMOD },
            { PropertyName.USAGE_TOOL_REQUIREDSKILLLEVEL, IntStat.USAGE_REQUIREDSKILLLEVEL },
            { PropertyName.USAGE_USERANIMATIONREPEATCOUNT, IntStat.USAGE_USERBEHAVIORREPEATCOUNT },
            { PropertyName.ACTIVATION_TYPE, IntStat.ACTIVATION_TYPE },
            { PropertyName.PORTALSCENE, IntStat.TRAVEL_PORTALSCENE },
            { PropertyName.NPC_DEATHLOOTMINQUANTITYOVERRIDE, IntStat.DEATH_LOOTMINQUANTITYOVERRIDE },
            { PropertyName.NPC_DEATHLOOTMAXQUANTITYOVERRIDE, IntStat.DEATH_LOOTMAXQUANTITYOVERRIDE },
            { PropertyName.NPC_DAMAGETYPE, IntStat.NPC_DAMAGETYPE },
            { PropertyName.ITEM_VALIDTARGETWEENIETYPE, IntStat.USAGE_VALIDWEENIETYPE },
        };

        public static readonly Dictionary<PropertyName, LongIntStat> PROPERTY_NAME_TO_LONG_INT_STAT = new() {
            { PropertyName.GAMEPLAYSTATISTICS_DEATHEXPERIENCE, LongIntStat.DEATHXP },
            { PropertyName.RADARCOLOR, LongIntStat.RADARCOLOR },
        };

        public static readonly Dictionary<PropertyName, PositionStat> PROPERTY_NAME_TO_POSITION_STAT = new() {
            { PropertyName.USAGE_REQUIREDLOCATION, PositionStat.USAGE_REQUIREDLOCATION },
            { PropertyName.USAGE_REQUIREDLOCATIONTSYSMIN, PositionStat.USAGE_REQUIREDLOCATIONTSYSMIN },
            { PropertyName.USAGE_REQUIREDLOCATIONTSYSMAX, PositionStat.USAGE_REQUIREDLOCATIONTSYSMAX },
        };

        public static readonly Dictionary<PropertyName, StringInfoStat> PROPERTY_NAME_TO_STRING_INFO_STAT = new() {
            { PropertyName.NAME, StringInfoStat.NAME },
            { PropertyName.DESCRIPTION, StringInfoStat.DESCRIPTION },
            { PropertyName.ITEM_PLURALNAME, StringInfoStat.PLURALNAME },
            { PropertyName.USAGE_SUCCESSMESSAGE, StringInfoStat.USAGE_SUCCESSMESSAGE },
            { PropertyName.PLURALNAME, StringInfoStat.PLURALNAME },
            { PropertyName.BOOK_SOURCE, StringInfoStat.BOOK_SOURCE },
            { PropertyName.INSCRIPTION, StringInfoStat.INSCRIPTION },
            { PropertyName.AUTHORNAME, StringInfoStat.AUTHORNAME },
            { PropertyName.USAGE_CRITICALSUCCESSMESSAGE, StringInfoStat.USAGE_CRITICALSUCCESSMESSAGE },
            { PropertyName.STORELOCATION, StringInfoStat.STORELOCATION },
        };

        public static readonly Dictionary<PropertyName, StringStat> PROPERTY_NAME_TO_STRING_STAT = new() {
            { PropertyName.PORTALDESTINATION, StringStat.TELEPORTDESTINATIONSTR },
        };

        public PackageType packageType => PackageType.PropertyMapper;

        public Dictionary<PropertyName, uint> propServer; // m_hashPropServer
        public Dictionary<PropertyName, uint> propClient; // m_hashPropClient

        public PropertyMapper(AC2Reader data) {
            data.ReadPkg<AAHash>(v => propServer = v.to<PropertyName, uint>());
            data.ReadPkg<AAHash>(v => propClient = v.to<PropertyName, uint>());
        }
    }
}
