namespace AC2RE.Definitions;

// Enum PrimType
public enum PrimType : uint {
    UNDEF = 0,
    POINTLIST = 1, // PRIMTYPE_POINTLIST
    LINELIST = 2, // PRIMTYPE_LINELIST
    LINESTRIP = 3, // PRIMTYPE_LINESTRIP
    TRIANGLELIST = 4, // PRIMTYPE_TRIANGLELIST
    TRIANGLESTRIP = 5, // PRIMTYPE_TRIANGLESTRIP
    TRIANGLEFAN = 6, // PRIMTYPE_TRIANGLEFAN

    INVALID = 0x7FFFFFFF, // PRIMTYPE_INVALID
}
